# Generated by Django 5.1.2 on 2025-10-27 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('site', models.CharField(blank=True, default='', max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_warn', models.FloatField(default=2.0)),
                ('high_warn', models.FloatField(default=8.0)),
                ('low_crit', models.FloatField(default=0.0)),
                ('high_crit', models.FloatField(default=10.0)),
                ('hysteresis', models.FloatField(default=0.3)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rule', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(choices=[('NORMAL', 'NORMAL'), ('SEVERE', 'SEVERE'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'ts'], name='core_measur_device__97ee8b_idx'), models.Index(fields=['state', 'ts'], name='core_measur_state_61745b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10)),
                ('severity', models.CharField(choices=[('SEVERE', 'SEVERE'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_role_index', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'status', 'opened_at'], name='core_ticket_device__4c1433_idx')],
            },
        ),
    ]
