# Generated by Django 5.1.2 on 2025-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_acked_at_ticket_acked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reminder_interval_min',
            field=models.IntegerField(default=30),
        ),
    ]
