# Generated by Django 5.1.2 on 2025-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_last_notified_at_ticket_reminder_interval_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='max_temp',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='device',
            name='min_temp',
            field=models.FloatField(default=5.0),
        ),
    ]
